### ISSUE TITLE
Not possible to open the multibranch timeline is some element aren't available and visible in the workspace

### ISSUE THREAD

**Issue by dvojtise** [eclipse/gemoc-studio-execution-moccml#57]
When launching the concurrent engine (Sigpml or tfsm)

the timeline may fail with 
```

java.lang.NullPointerException
	at org.eclipse.gemoc.timeline.view.AbstractTimelineView.setTimelineProvider(AbstractTimelineView.java:638)
	at org.eclipse.gemoc.addon.eventscheduling.timeline.views.timeline.EventSchedulingTimeLineView.disposeTimeLineProvider(EventSchedulingTimeLineView.java:188)
	at org.eclipse.gemoc.addon.eventscheduling.timeline.views.timeline.EventSchedulingTimeLineView.configure(EventSchedulingTimeLineView.java:142)
	at org.eclipse.gemoc.addon.eventscheduling.timeline.views.timeline.EventSchedulingTimeLineView.update(EventSchedulingTimeLineView.java:293)
	at org.eclipse.gemoc.addon.eventscheduling.timeline.views.timeline.EventSchedulingTimeLineView.engineSelectionChanged(EventSchedulingTimeLineView.java:194)
	at org.eclipse.gemoc.executionframework.ui.views.engine.EnginesStatusView.fireEngineSelectionChanged(EnginesStatusView.java:343)
	at org.eclipse.gemoc.executionframework.ui.views.engine.EnginesStatusView$1.selectionChanged(EnginesStatusView.java:89)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
```

Actually, once it crashed that way, it not possible to open it without restarting the eclipse

the only way I found to correctly use the timeline is to:
- first open the timeline and make sure is it visible (if it is stacked in a tab and not visible, the same error occurs)
- then launch the simulation (with the multibranch addon)

**Comment by jdeantoni** [comment]
True, this is a race condition which holds for years. I never found how to correct it and I'm using the workaround you described
