### ISSUE TITLE
RuntimeException when creating or restoring branches while looking for setter in ModelStateHelper

### ISSUE THREAD

**Issue by dvojtise** [eclipse/gemoc-studio-execution-moccml#58]
In the current studio, both sigpml and tfsm examples fail to navigate the trace

Navigating raise errors such as:  (using the tfsm example)
```
java.lang.RuntimeException: not method found for org.eclipse.gemoc.example.moccml.tfsm.tfsm.impl.StateImpl::setcurrentState
	at oncurrenttfsm.xdsml.api.impl.OncurrentTFSMModelStateHelper.restoreModelState(OncurrentTFSMModelStateHelper.java:107)
	at org.eclipse.gemoc.execution.concurrent.ccsljavaengine.eventscheduling.trace.EventSchedulingModelExecutionTracingAddon.restoreModelState(EventSchedulingModelExecutionTracingAddon.java:222)
	at org.eclipse.gemoc.execution.concurrent.ccsljavaengine.eventscheduling.trace.EventSchedulingModelExecutionTracingAddon.restoreModelState(EventSchedulingModelExecutionTracingAddon.java:151)
	at org.eclipse.gemoc.execution.concurrent.ccsljavaengine.eventscheduling.trace.EventSchedulingModelExecutionTracingAddon.access$4(EventSchedulingModelExecutionTracingAddon.java:149)
	at org.eclipse.gemoc.execution.concurrent.ccsljavaengine.eventscheduling.trace.EventSchedulingModelExecutionTracingAddon$2.doExecute(EventSchedulingModelExecutionTracingAddon.java:135)
	at org.eclipse.emf.transaction.RecordingCommand.execute(RecordingCommand.java:135)
	at org.eclipse.emf.workspace.EMFCommandOperation.doExecute(EMFCommandOperation.java:119)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:496)
	at org.eclipse.emf.workspace.impl.WorkspaceCommandStackImpl.doExecute(WorkspaceCommandStackImpl.java:208)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:219)
	at org.eclipse.gemoc.executionframework.engine.core.CommandExecution.execute(CommandExecution.java:33)
	at org.eclipse.gemoc.execution.concurrent.ccsljavaengine.eventscheduling.trace.EventSchedulingModelExecutionTracingAddon.internalBranch(EventSchedulingModelExecutionTracingAddon.java:145)
	at org.eclipse.gemoc.execution.concurrent.ccsljavaengine.eventscheduling.trace.EventSchedulingModelExecutionTracingAddon.branch(EventSchedulingModelExecutionTracingAddon.java:109)
	at org.eclipse.gemoc.addon.eventscheduling.timeline.views.timeline.EventSchedulingTimeLineView.branchIfPossible(EventSchedulingTimeLineView.java:276)
	at org.eclipse.gemoc.addon.eventscheduling.timeline.views.timeline.EventSchedulingTimeLineView.handleDoubleCick(EventSchedulingTimeLineView.java:239)
	at org.eclipse.gemoc.addon.eventscheduling.timeline.views.timeline.EventSchedulingTimeLineView.access$0(EventSchedulingTimeLineView.java:218)
	at org.eclipse.gemoc.addon.eventscheduling.timeline.views.timeline.EventSchedulingTimeLineView$1.mouseDoubleClick(EventSchedulingTimeLineView.java:114)

```

**Comment by dvojtise** [comment]
@jdeantoni apprently you have some commits in your branch https://github.com/eclipse/gemoc-studio-execution-moccml/commits/FormalAnalysisByExhaustiveSimulation (such as https://github.com/eclipse/gemoc-studio-execution-moccml/commit/598819f8932d6873f93d447a48d81a7c494b48ab) that are related

will need ot see together which version is best to start with (your branch or my current fix) and then optionnaly combine them.

**Comment by jdeantoni** [comment]
@dvojtise could you please check that it is not solved in the merged version ?

**Comment by dvojtise** [comment]
It is solved for sigpml and tfsm thanks to https://github.com/eclipse/gemoc-studio-execution-moccml/pull/62
I have other issue with other languages but let's close this one
